### ISSUE TITLE
Wake on LAN different behaviour in Win 8.1 and 10

### ISSUE THREAD

**Issue by TPunkt** [basildane/WakeOnLAN#1]
Hello,

I just installed a new NAS (OpenMadiaVault) and can't wake it up with Wake on LAN tool running on a Win 8.1 PC. With Win 10 on antoher PC, same tool, no problem.

Thanks a lot in advance for your help.

Kindest regards

TPunkt

**Comment by basildane** [comment]
Are the 8.1 and 10 computers in the same subnet?
Are you sure you have the mac address entered correctly on the 8.1 machine?

You can run the "listener" on the 10 machine, then send a wake up from the 8.1 machine, does the 10 machine see it?

**Comment by TPunkt** [comment]
Thanks a lot for your quick reply. Using the listener I found out that 
my Win 8.1 PC was using another subnet. Reason was the installation of 
VirtualBox some weeks ago. Now everything is working fine again.

Thanks a lot for your help.

Kindest regards

Am 05.01.2016 um 18:27 schrieb basildane:
>
> Are the 8.1 and 10 computers in the same subnet?
> Are you sure you have the mac address entered correctly on the 8.1 
> machine?
>
> You can run the "listener" on the 10 machine, then send a wake up from 
> the 8.1 machine, does the 10 machine see it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/basildane/WakeOnLAN/issues/1#issuecomment-169071389>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
