### ISSUE TITLE
New Feature Suggestion: Open Homepage

### ISSUE THREAD

**Issue by jpdonato** [basildane/WakeOnLAN#122]
Hi, I have a new feature suggestion for WakeOnLAN. In its main window, right-clicking a host brings up a menu that includes several items including "Remote Desktop". This is a very convenient feature to quickly access hosts and we use it often. However, more and more WakeOnLAN-enabled devices in our LAN, such as printers, NAS, switches and more, do not support RDP but rather HTTP(S). In other words, one cannot connect to them via Windows Remote Desktop but must instead open a browser HTTP (or HTTPS) connection to the device's homepage, which is typically at its IP address (which WakeOnLAN knows) and typically at the default port. It would thus be a very convenient new feature to have an additional right-click menu item, named for example "Open Homepage", that would simply launch the default browser at the IP address of the device. (There should be an option to select whether HTTP or HTTPS, since some devices support one and not the other.) Thanks again for a great program! Cheers

**Comment by basildane** [comment]
Good news, we are working on that.  Right now in beta, you can specify Putty as the remote desktop method.  Your idea is better, I'm going to get on that as soon as I can get some time.  Somehow it needs to be a universal parameter, maybe a URI, I need to investigate.

**Comment by basildane** [comment]
rdp://host
putty://host
https://host

**Comment by jpdonato** [comment]
Thank you, that's great! - even if less secure, also having http://host would be most useful since some older devices don't work well, or at all, with https.


Cheers

________________________________

**Comment by basildane** [comment]
Please help me test.  I built a beta that I am using myself, it's working great.
[2.11.23 beta 21](https://cloud.aquilatech.com/s/R9ZXsSBDrK9tWPZ)

You can use the help on the properties page to understand what to put in the remote desktop command field.

As it says, you use rdp:...  reference an .RDP file, putty:host, http or https://host, cmd:any-command.

I need to clean up the documentation to make it clearer.
This is going to be a major change, we are changing dotnet versions, and anything you had in the RDP field before has to be reentered, because the function has changed significantly.

Let me know how this works for you or if you have a question.

**Comment by basildane** [comment]
I just found a bug, if you click on remote without having configured that host, it will crash.  I'll fix that in the next build tomorrow.

**Comment by jpdonato** [comment]
Hi, I downloaded version 2.11.23 Beta 21 today and ran a few tests. It works great! I tested it on Windows 10 version 1803 and its Remote Desktop menu item correctly opened my default browser (Edge) with the contents of the configured Command field, like http://host. I did notice that attempting to run WOL's Remote Desktop without a configured command - or an invalid command like abracadabra - will indeed cause it to crash. One issue I ran into though (my brain, not the program), is that initially I didn't recall how to configure it again for those RDP (i.e. non-HTTP) hosts. Quickly enough I remembered, rdp:host and it worked fine. I fear regular users may not understand how to "re-configure" RDP and so perhaps below the Command field a few brief examples could be stated like rdp:host, http:host, etc.


Cheers


________________________________

**Comment by AJBello1437** [comment]
Scheduled tasks to wake up computers at specified time no longer work with this build.

**Comment by basildane** [comment]
Hi, what is the exact problem you are having with scheduled tasks?  I am testing and it is working here, no change.

**Comment by AJBello1437** [comment]
Access denied message error, when the task is supposed to run.
Installing the release version makes it work again.

**Comment by basildane** [comment]
If you go into the task General Tab, reenter the user id  / password, does it work?

**Comment by AJBello1437** [comment]
Tried that and no good.



Sent via the Samsung Galaxy Note8, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by basildane** [comment]
@AJBello1437 I don't know what to say.  That code has not changed.  The only thing is that your credentials will need to be reentered.  Mine did.  Once I entered my userid and password into scheduler, it worked just like before.
