### ISSUE TITLE
Computers always greyed out on Windows Server 2016

### ISSUE THREAD

**Issue by Olorin1611** [basildane/WakeOnLAN#130]
I've used this product for a number of years (and Thank You by the way!).  A few months ago it stopped functioning properly - all the PCs appeared greyed out.  I tried upgrading the software and that had no effect so I put this on the back burner until I had a moment to look it over again.  Today I removed the software and cleared the dircectory "c:\ProgramData\Aquila Technology" , and removed the registry key under HKLM\Software\Aquila Technology".  This occurs even if I use "Run as Administrator" to pre-elevate the application.  I then re-installed the software and manually added a test computer.  It still shows greyed out and status as "unknown".   I've gone to the firewall control panel and specifically added this application and given it full access (note: the machine firewall is turned off at the moment anyway so that shouldn't have been a problem - just covering the bases).  I've noticed that the software uses Netbios calls (based on the general documentation you've posted) so I set the "Computer Browser" service to manual and turned it on and relaunched the application - still the same behavior.   Note - during testing if I get the same results I relaunch the app using "Run as Administrator" to pre-elevate so that I can make sure that is not a mechanism getting in the way. 

I like the software and would like to continue using it.  A screenshot of what I see follows.  Do you have any suggestions please?

Software Version is 2.12.2.0
OS: Windows Server 2016 

I have this on this system as I can guarantee it's always on and the software will be running.  

![image](https://user-images.githubusercontent.com/45795183/49811370-24f41180-fd31-11e8-9013-179c6f9f079b.png)

Your assistance is appreciated - thanks!

**Comment by basildane** [comment]
Hi, just click the "Pinger" button to enable real-time status of remote servers.

**Comment by basildane** [comment]
Glad I could help, enjoy!
