### ISSUE TITLE
Using 'Search' feature

### ISSUE THREAD

**Issue by ghq55** [basildane/WakeOnLAN#133]
Good morning,

When I use the 'Search' feature and add a machine, it shows up as being "uninitialized". What do I have to do to initialize it? Thanks!   
![image](https://user-images.githubusercontent.com/45662359/50835939-f9f7e000-1325-11e9-87ff-b109b7164e7c.png)

**Comment by basildane** [comment]
What is the default language you are using on your computer?  And are you using the English setting in WOL?

I think the message you are seeing means that WOL cannot ping the host.  Can you open a command prompt and manually ping it?

**Comment by ghq55** [comment]
Hi,

I'm using English. I think the issue was that this machine had already been added. When I deleted it and did the search again, it came up as being online! Think I'm all set! Thanks!

**Comment by basildane** [comment]
Well, glad you have it working!
