### ISSUE TITLE
WOL is no longer working for me

### ISSUE THREAD

**Issue by clriis** [basildane/WakeOnLAN#137]
I've been a happy user of WOL for +3 years now to help me in operating my two Windows 10 boxes at home. 
But with a new update from MS the PCs no longer responds to a magic packet from WOL. I can still use "Wake on LAN" from my android phone and also "wakeonlan" from a Linux box works.
Any thoughts?

**Comment by basildane** [comment]
That's very odd.  The only thing that comes to mind is possibly the local firewall settings.  First thing to do though is to install WOL on the target and run the listener, to see exactly what it is receiving.

**Comment by clriis** [comment]
I've actually never installed anything WOL on the target....
This little batch has been working fine for years:
---
@echo off
ping -n 1 -w 100 192.168.1.12 | find "TTL" && goto START
"C:\Program Files\Aquila Technology\WakeOnLAN\WakeOnLanC.exe" -w -mac F0-DE-F1-C4-A0-97
delay 25
:START
start /PGM "D:\1Program\192.168.1.12.rdp"

---

**Comment by clriis** [comment]
I'm So So sorry to have disturbed you...it was the "port 9" issue!!!...had been playing around with SMB protocols and at some point managed to engage Simple TCP/IP.
I will make sure to make an extra donation

**Comment by basildane** [comment]
No bother at all, glad you figured it out!
