### ISSUE TITLE
Random Forced Power Off to all PC's

### ISSUE THREAD

**Issue by KFLTech** [basildane/WakeOnLAN#142]
This is the second time this has happened at a random time of the day.  I have nothing scheduled in the scheduler for this time, however all the PC's in our Library were "Forced Shutdown".  According to the log file, the PC's shut off at 1:49 PM with ID code 2.  Since I am the only one who has access to this application, I am not sure what happened.  There is no way to tell what made the PC's automatically shut down at this random time.  Any advice or ideas are welcome.

![WOL log file](https://user-images.githubusercontent.com/49040850/55185149-1e679980-516a-11e9-90cb-176fa6797e75.JPG)
![WOL Schedule](https://user-images.githubusercontent.com/49040850/55185150-1f003000-516a-11e9-8eb9-69e73963a8ea.JPG)

**Comment by basildane** [comment]
The first thing I would do is go to one of those machines and investigate the event log.  You should see who/what caused the shutdown.
Also, unlikely, but you can look at scheduled tasks directly (not through the wol interface).  See if there are any other scheduled tasks that are initiating a shutdown.  A shutdown can come from anywhere that has authority, even the command line.  The event log should at least tell us who and where started it.

**Comment by basildane** [comment]
Also, check the scheduled task history on this computer at 1:50.  Did a task fire?  Maybe one was manually fired?

**Comment by KFLTech** [comment]
Thanks for the ideas.  Didn't fix the issue yet, but this isn't a WOL issue.  More likely a rogue script/windows update issue.  Going to change the Domain Admin PW since that was the account that created/allowed the event.  Thanks again.
