### ISSUE TITLE
WOLAgent no longer working after latest Security update kb4503276 on Server 2012R2

### ISSUE THREAD

**Issue by simoncraddock** [basildane/WakeOnLAN#153]
Since installing Windows update kb4503276 yesterday on our 2 servers we can no longer remote boot. Anyone else having the same issue?

Listener on a PC picked up nothing from Windows Server 2012R2 (on same subnet)
Listener on a PC picked up WOL signal from a Win10 fine.

**Comment by basildane** [comment]
That sounds like the local firewall rule on the 2012 server got changed.  UDP port 9 open?

**Comment by simoncraddock** [comment]
We turned off the firewalls on the server and still couldn't send a WOL signal

**Comment by simoncraddock** [comment]
Just tried the main WOL GUI app on the server and couldn't wake anything up on the same subnet either, so it's not just the Agent that's stopped working. Working fin on Windows 10 oddly.

**Comment by basildane** [comment]
I have one 2012 server left at home, and it has that update in the queue to install tonight.  I'll update it and test...

**Comment by simoncraddock** [comment]
ok thanks.

**Comment by basildane** [comment]
I have updated my 2012 R2 server and installed WOL on it.
After adding UDP port 9 to the firewall inbound rules, I ran the listener.
I sent a test to it from another machine.

The WOL packet was received normally.

**Comment by simoncraddock** [comment]
Hi it's sending from the servers to desktops that stopped working. We can't wake anything up from the Servers since the Microsoft updates were installed.

Will try again today.

**Comment by simoncraddock** [comment]
No joy. Installed both the WOL software on a different 2012R2 Server on the same subnet as my own PC and couldn't send the WOL packet from the Server to the Listner on my PC. 

Only solution currently seems to be putting a Win10 box at both sites to run the WOLAgent so we can wake up desktop systems.

**Comment by simoncraddock** [comment]
Ok I thing I've stumbled onto something. Sometimes a field is or isn't visible in the WOL GUI and thats the drop down to select the IPv4 NIC to use. If the field is visible and I select the LAN address presented and OK. I can then wake up the PC in question. However if I then go back into it sometimes it's gone and WOL no longer works.

**Comment by basildane** [comment]
Whoa, I think that field went away a long long time ago.  It was replaced by smarter code that automatically controls the nic.

What is the version of WOL you are using?

**Comment by simoncraddock** [comment]
Most recent. Like I said sometimes it's visible, sometimes it's not. Very odd.

**Comment by basildane** [comment]
please send a screenshot of that tab with the field.

**Comment by simoncraddock** [comment]
It'll have to wait until Monday now. But will do.

**Comment by basildane** [comment]
In the meantime, I will review that code later tonight...

**Comment by simoncraddock** [comment]
Ok cheers. I've only seen it on the virtual machines so far that obviously have multiple NICs.

**Comment by simoncraddock** [comment]
Just remoted in to our server to continue where I left off (bit of free time tonight).

Update:

I've completely removed WOL GUI from one of the servers and rebuilt the list of machines at one site by getting rid of the old 'machines.xml' file and adding in 1 by 1 a few systems. So far so good I can wake them up..

If I then go back to the original 'machines.xml' file from the previous upgraded installation then suddenly I start having problems with errors referring to 'padding' and inability to wake anything up.

Going back to the new 'machines.xml' file, all seems well again.

It would seem from observation that the XML file is the issue, example entry below...

**### Working**

<Machine>
    <Name>C0313</Name>
    <MAC>B0:83:FE:5A:2A:AE</MAC>
    <IP>10.16.4.29</IP>
    <Broadcast>255.255.255.255</Broadcast>
    <Netbios>C0313</Netbios>
    <Method>0</Method>
    <Emergency>false</Emergency>
    <ShutdownCommand />
    <Group>Sidings Court</Group>
    <UDPPort>7</UDPPort>
    <TTL>128</TTL>
    <RemoteCommand />
    <Note></Note>
    <UserID />
    <Password>z4TNiLtxUFpYg1W8pQM5bg==</Password>
    <Domain />
    <ShutdownMethod>WMI</ShutdownMethod>
    <KeepAlive>false</KeepAlive>
    <RepeatCount>1</RepeatCount>
  </Machine>

**### Not working**

<Machine>
    <Name>C0313</Name>
    <MAC>B0:83:FE:5A:2A:AE</MAC>
    <IP>10.16.4.29</IP>
    <Broadcast>255.255.255.255</Broadcast>
    <Netbios>C0313</Netbios>
    <Method>0</Method>
    <Emergency>false</Emergency>
    <ShutdownCommand />
    <Group>Sidings Court</Group>
    <UDPPort>7</UDPPort>
    <TTL>128</TTL>
    <Adapter>10.16.1.9</Adapter>
    <RDPPort>3389</RDPPort>
    <Note></Note>
    <UserID />
    <Password>z4TNiLtxUFpYg1W8pQM5bg==</Password>
    <Domain />
    <ShutdownMethod>WMI</ShutdownMethod>
  </Machine>

**Comment by simoncraddock** [comment]
working

<Machine>
    <Name>C0313</Name>
    <MAC>B0:83:FE:5A:2A:AE</MAC>
    <IP>10.16.4.29</IP>
    <Broadcast>255.255.255.255</Broadcast>
    <Netbios>C0313</Netbios>
    <Method>0</Method>
    <Emergency>false</Emergency>
    <ShutdownCommand />
    <Group>Sidings Court</Group>
    <UDPPort>7</UDPPort>
    <TTL>128</TTL>
    <RemoteCommand />
    <Note></Note>
    <UserID />
    <Password>z4TNiLtxUFpYg1W8pQM5bg==</Password>
    <Domain />
    <ShutdownMethod>WMI</ShutdownMethod>
    <KeepAlive>false</KeepAlive>
    <RepeatCount>1</RepeatCount>
  </Machine>

**Comment by basildane** [comment]
Could you upload that bad xml file to [me here](https://cloud.aquilatech.com/s/cKHVPHPXfaYdbjn) ?
I wouldn't post parts of here by the way...

**Comment by simoncraddock** [comment]
I'll try I'm working via Citrix on a machine with no email. I'll try boot up my own laptop thats still in the office.

**Comment by simoncraddock** [comment]
ok thats uploaded.

**Comment by simoncraddock** [comment]
Tried WOLAgent no joy sadly.

Sadly I can't get the listener working on the servers as it reports 'An attempt was made to access the socket in a way forbidden by its access permission' which I've been unable to resolve.

**Comment by basildane** [comment]
Do you have "simple tcp services" installed on that machine?

**Comment by simoncraddock** [comment]
No, I followed your guide but it's not installed.

**Comment by basildane** [comment]
OK, let me make sure I understand.
After upgrading to the latest version, the WOL listener see's incoming packets on the 2012 server, where it did not before.
Also, the Agent still does not repeat packets.

Then I have a theory.  The default interface on that machine has changed and Agent is no longer using the correct interface.  That program was only designed for one NIC.

I need a little time to look at Agent to see what we can do...

**Comment by simoncraddock** [comment]
Almost.

We are unable to run the listener on the servers due to that socket error. We never needed the listener on previous version as we had no issues.

We are now unable to wake up remote systems using the Agent after Wednesday lunchtime when MS Updates were applied and it was rebooted.

Thanks for your assistance.

**Comment by simoncraddock** [comment]
This seems to affect all our VM's. 
Systems we've never had WOLagent installed don't work if its installed and used as the broadcast address.
All were updated Tuesday/Wednesday with latest MS updates

**Comment by simoncraddock** [comment]
Just an idea is there anyway to query what NIC the WOLagent is picking up?

**Comment by basildane** [comment]
You closed the issue?
Yes, we can determine which NIC it is reading, but I was going to add a parameter to let you specify which NIC to use.  Is this no longer necessary?

**Comment by simoncraddock** [comment]
No its still open isn't it?
Selecting NIC would be appreciated, thank you.

**Comment by basildane** [comment]
OK, I have a [beta release](https://cloud.aquilatech.com/s/8GD3rNCdSeEiJoN) ready.
This will create a file in C:\program data\aquila technology\agent\config.xml.

That file by default looks like this:
`<?xml version="1.0" encoding="utf-8" ?>
<agent>
  <listen>
    <port>9</port>
    <address>0.0.0.0</address>
  </listen>
  <send>
    <port>9</port>
    <address>255.255.255.255</address>
  </send>
</agent>`


You can change the listen address from 0.0.0.0 to the IP of the interface you want to listen on.
I have tested it here (a little) and it works for me.

**Comment by simoncraddock** [comment]
Ok many thanks for this, I wasn't expecting someting so soon.

I had a quick try but could get anything working but I'll have more time Tuesday as I'm not going to get opportunity to look at it Monday.

I'll let you know how I get on. Again many thanks.

**Comment by basildane** [comment]
When you have time, please run "netstat -n" from a command line and see if the server is listening on 0.0.0.0:9 or the IP you designated.

**Comment by simoncraddock** [comment]
It would appear not..

I tried breifly again this morning and one thing I noticed was that from ther server I couldn't wake anything up using port 9 from the GUI app. I had to change to port 7. It's like port 9 is completely locked down by something.

Netstat -ab reports
  UDP    10.16.1.9:9            *:*
  UDP     10.16.1.9:137       *.*

**Comment by basildane** [comment]
This is good.  You've found the problem - some program has the port locked.  I think netstat can show us which program has port 9.

**Comment by simoncraddock** [comment]
Ok spent a little bit of time this evening and have you'll be pleased to hear I've figured out whats happening and have it working again!

Ok here's what I discovered..

On the Server (@site 2) with WOLAgent installed, the seperate GUI app aslo installed on the same server is blocked from accessing port 9. Hence why I could only seem to get port 7 working earlier. Other apps however can access port 9 no problem.

With the GUI open on the remote server (@site 2) alongside WOLAgent the signals to WOLAgent seem to be ignored if I send a WakeUp request from my laptop (@site 1). I'll be in a better way to test that theory on Tuesday (possibly late Monday).

But it is once again working so I'm incredibly gratified for your quick support and patience and will sort out a donation if I can get my dept. manager to approve it. If not I'll do it myself as I'm very grateful for your help. Thank you.

**Comment by basildane** [comment]
This is a relief.  Glad it's working.

**Comment by Twincharger** [comment]
Dear basildane, thanks for this very useful software. Just to let you know I was lucky to find this thread because the latest official 1.2.0.0 release will not install on a German Windows Server 2012R2 system with the following error. In English it says the account name is invalid or not present or the password for the specified account is invalid. 1.4.0.0 beta installed just fine and our VPN clients can finally wake up machines on our LAN. Maybe it is time to release the new version? Thanks!

![grafik](https://user-images.githubusercontent.com/56991490/67547655-f04a3800-f6ff-11e9-8784-1441f4858c60.png)

**Comment by Gamecollector** [comment]
I have the same problem. Where do i get Agent 1.4.0.0 beta?

**Comment by basildane** [comment]
Sorry I forgot to publish it.  [v1.4.0](https://github.com/basildane/WOLAgent/releases/tag/v1.4.0)

**Comment by Gamecollector** [comment]
thank you very much!
