### ISSUE TITLE
SOLVED: PCs suddenly wake up on their own

### ISSUE THREAD

**Issue by holocafe** [basildane/WakeOnLAN#154]
Hi Basildane!

I've been running your great tool now for quite some time, it worked like a charm. I can't remember having changed anything, but now some of my PCs wake up on their own after setting them to shut down via WOL. They even re-awaken when I shut them down via the windows shutdown command, so the network card should not be put into "listening" mode this way actually. I could never wake up any PCs after shutting them down like this manually, but now I can, and they even do it on their own after around 5 minutes of the shutdown. 

Also strange is that the PCs that remain working properly are shown as "grayed out", as if they are disconnected from the network. And the ones that are re-awakening are shown as blue icons (as offline). So the system marks them up (see screenshot).. Have you ever heard of this issue and can you imagine what the cause could be?

Best,
Vriend

**Comment by basildane** [comment]
If you suspect you are getting WOL packets that are waking up the machines, you can run the "listener" function on another computer.  It will record and display every WOL it sees on the network.

However, I strongly suspect you are not getting WOL packets waking up those machines.  More likely is that you have other NIC options set, such as "wake on link" or "wake on ping", and those are causing the machines to wake up on their own.  Go to one of those computers and lets investigate the NIC adapter settings.  You can post screenshots here if you like.

As for the greyed out machines, they would be greyed out like that if the configuration in WOL is incomplete.  The FQDN/IP is not correct or the IP is not route-able.  From the WOL computer, can you ping 192.168.178.11?

**Comment by basildane** [comment]
The status, online, offline is a result of a ping.  Unknown would indicate WOL got an error trying to ping that machine.

**Comment by holocafe** [comment]
Hi Basildane, thank you for your suggestions!

Solved the issue: in the network adapter settings the "setting" "wake on pattern recognition" was enabled. This caused the issue only on some specific mainboards. Hope this helps somebody!
Also thank you for the grayed out machines hint. There was probably a router issue - reset it and set it up again solved it. 

Thanks again for your great support, donated :)

**Comment by basildane** [comment]
Very happy you have it working now.  Thank you very much for the donation!
