### ISSUE TITLE
Wakeonlan commands for linux (Raspbian of RaspberryPi) shutdown

### ISSUE THREAD

**Issue by AlbertUy** [basildane/WakeOnLAN#155]
Hi, I can not shutdown remotly a raspberry pi, I tried many ways but don´t worked it. Putty is ready installed and worked well in a windows pc. 
C:\Program Files \Putty\plink.exe -ssh -pw password root@machine /sbin/poweroff don´t work.
I added command sudo at poweroff and nothing happens. 
any suggestions? Someone cgive a right example? Thank´s

**Comment by basildane** [comment]
Are you able to do the shutdown manually from the command line?  Leave WOL out of the test to simplify it.  Maybe the spaces in your command line require it to be in quotes?

**Comment by AlbertUy** [comment]
I have been able to successfully turn off the Raspberry Pi through Putty and Powershell, but I can't find the right command to do it through WakeOnLan. I already tried placing the quotes, in the "C: \ Program Files \ PuTTY \ plink.exe" part without results. Can you write me an example to prove it? Thank´s

**Comment by basildane** [comment]
I'm having trouble now because Ubuntu has removed the "root" user.  Need to send the command with sudo...

**Comment by AlbertUy** [comment]
Solved! Line command in WakeOnLan: ssh pi@192.168.1.33 sudo poweroff
Solution Webpage:
https://rm-rf.es/login-ssh-sin-password-de-forma-rapida-y-sencilla/

**Comment by basildane** [comment]
Glad you figured it out and thank you for posting the solution.  I'm going to read about it as soon as I have time.  Thanks!
