### ISSUE TITLE
Works only when connected to the same network

### ISSUE THREAD

**Issue by oguchihy** [basildane/WakeOnLAN#163]
Any reason why this does not work from any internet connection? It only works when both computers are on the same network.

**Comment by basildane** [comment]
WOL packets are "broadcast" packets and cannot be sent directly on the Internet.  You can use the Agent on a local server make this work.  [https://wol.aquilatech.com/agent/](https://wol.aquilatech.com/agent/)

**Comment by oguchihy** [comment]
Will the Agent work on a desktop PC (as opposed to a Server), or can the PC be "tricked out" as a server for this purpose?
Thanks for understanding my question even though it might not have been clear. I read a lot about WoL's before trying out some, but none of the literature made the differentiation that you have so aptly pointed out (and a solution, to boot).
