### ISSUE TITLE
Shutdown: I had to struggle with it!

### ISSUE THREAD

**Issue by smz** [basildane/WakeOnLAN#174]
Hello, and first of all let me thank-you for your splendid application which I'm using while I'm on the move to access my home network (_all Windows 10 PCs in a WORKGROUP_), through an L2TP VPN.

Everything is working fine, but I had to struggle a little bit with the remote shutdown.

After several tests, fiddling and googling, I've found what was missing:
1. Enable WMI through Windows Defender firewall
2. add the following policy:

`reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1`

Contrary to what is stated in https://wol.aquilatech.com/help/shutdown-host/ shutting down seems to be totally reliable now.

So... there is no issue at all, but may I suggest that you add the above information to the FAQs?

Again many thanks!

**Comment by basildane** [comment]
Thank you for taking the time to help everyone.  I will add your comments to the help page as you suggested.  I hope to be able to get to it this weekend.
Glad you had success!
