### ISSUE TITLE
WOL- screen remains dark

### ISSUE THREAD

**Issue by milan254** [basildane/WakeOnLAN#178]
When I send a "wake up" command via WOL Aquilqa from the desktop (klient) to the laptop (guest) , the mains connection indicator light comes on, the fan works and the listener displays the received packet but the screen remains dark. Computers work on lan inputs of the same router in the same subnet.
Note: when I change the task and send a "wake up" command from the laptop (klient) to the desktop (guest) the result is 100%.
I have tried almost all the advices from the internet without results. Please advise how to proceed.
best regards
milan strojný

**Comment by basildane** [comment]
WOL is to power on your computer, it sounds like that worked.  Can you explain a little more what is happening?
