### ISSUE TITLE
Limit to number of hosts? 

### ISSUE THREAD

**Issue by samasake** [basildane/WakeOnLAN#179]
I'm trying to consolidate all of our locations and after launching the program I hang on Not Responding. 

I'm wondering if there is a limit to hosts I can have? Perhaps I'm not waiting long enough for it to finish? 

I edited the machines.xml file to add all of my hosts. There are just over 200 machines. 

Thank you.

**Comment by basildane** [comment]
There should not be any hard limit.  Obviously pinging that many machines is a severe load on the client, so I break down the polling of hosts into blocks.  There is a setting in Options called "number of threads".  That setting determines how many blocks of hosts to ping at one time.

Another option is to break your hosts up into "groups".  You can define these "folders" on the left pane of the main interface.   For example, put all of the first floor hosts on "First Floor".  When you click on the folders, only the hosts in that folder will be polled.

Sorry I don't have any other useful advice at this time.  Are you on the latest version?

**Comment by samasake** [comment]
I was being impatient and waiting a bit longer was the solution. 

There were quite a few hosts for sure. I have been utilizing groups for organization sake but I keep it active on "all machines" so it was definitely taking some time. 

Thank you for your response!
