### ISSUE TITLE
pinger froze too often

### ISSUE THREAD

**Issue by abeulink** [basildane/WakeOnLAN#187]
Hi guys, 

I can't use WakeOnLan anymore, because after start WakeOnLan froze after a few seconds... 
My Windows version 21H1 (Build 19043.1110)
WakeOnLan version 2.12.4
I think the problem is Pinger of WakeOnLan. I need to disable the pinger by using command line. 
Because I had some problem with Pinger long ago. It frozed very few, I had to use Pinger very few, then it will be ok again.
But now impossible!!!

I have tried: uninstall WakeOnLan, restarting PC, install WakeOnLan... same problem.

To developer of WakeOnLan: please update your WakeOnLan!!! 
We really need a new version!!! Your WakeOnLan is becoming obsolete.

**Comment by basildane** [comment]
You can disable the pinger by default, by changing the config file.
You will find it here: C:\Users\[your name]\AppData\Local\Aquila_Technology\WakeOnLan.exe_Url_[random string]\2.12.4.0
The filename is user.config.

This file is XML, you can edit it with notepad if you like.  Find the line 
```
 <setting name="Pinger" serializeAs="String">
      <value>True</value>
 </setting>

```
And change True to False.  Then start WOL.

I would be interested in hearing more about what is wrong with ping.  Can you ping the machines yourself from the command line?

About updating the program, I would love to, but after 15 years I just do not have any time for these projects any more.  I hate to let it sit as much as you.  I have too many projects to keep up with now.

**Comment by abeulink** [comment]
Thanks, nice that I can start WakeOnLAN again.

After many tests: it seems that Pinger has a serious problem when the list contains more than 5 devices.
3 devices no problem
4 devices hiccup problem
5 devices start a small problem
6 and more devices, freezes WakeOnLan

Maybe Windows thinks my PC did a DOSS attack and Windows is trying to stop my mass pings, that's why WakeOnLan freezes I think.

I am using Microsoft Defender and Sentinel Agent from Microsoft, unfortunately I cannot disable them.

**Comment by Moopere** [comment]
@abeulink 

Running a fleet of 20H2 here, 30 + machines + servers, no problems with the pinger.

Its possible that something has gone wrong with 21H1.   How is WOL 'freezing' manifesting itself?  Are you getting a WOL not responsive message?  

We use MS defender here, though not SIEM, so perhaps thats the cause?

**Comment by abeulink** [comment]
HELLL YEAAAAAH I FINALLY FOUND A PROBLEM!!! 

Some one added ip address of network printer and named it as computername.
So printer causes frozes... weird problem.
I deleted printer from list, pinger works again on full list!!!

**Comment by basildane** [comment]
@abeulink Thank you for letting us know you found the problem!
