### ISSUE TITLE
Want add simple Chinese

### ISSUE THREAD

**Issue by Bit-Geek** [basildane/WakeOnLAN#189]
I want make simple Chinese for wake on lan.I will send you resx of simeple Chinese if you want add simple Chinese.

**Comment by basildane** [comment]
Hey Bit-Geek, i completely forgot to respond to you.  I apologize for that.
I appreciate your offer to update the resx file.  There are some problems.  I just don't have time anymore to publish updates to this primarily and I do not have a current "code signing key".

Did you find problems with the Chinese that we published before?
