### ISSUE TITLE
WakeUp error: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by ENV05** [basildane/WakeOnLAN#19]
After I updated WOL to 2.11.9, I am suddenly getting this error message. Nothing about my long-working configuration has changed. My system is Win7-32. FWIW, this is the error placed in the Event Viewer:
-	System	

		-	Provider		
					[ Name] 	WakeOnLan		

		-	EventID	1000	
					[ Qualifiers] 	0		

			Level	2	

			Task	0	

			Keywords	0x80000000000000	

		-	TimeCreated		
					[ SystemTime] 	2016-05-13T20:24:08.000000000Z		

			EventRecordID	248410	

			Channel	Application	

			Computer	Kripplekeeper	

			Security	

-	EventData	

			WakeUp error: An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by basildane** [comment]
Please check [here](http://wol.aquilatech.com/help/troubleshooting/listener.html)
