### ISSUE TITLE
please, show me "Ping TTL"

### ISSUE THREAD

**Issue by atti2000** [basildane/WakeOnLAN#20]
Hi, I'm a pc engineers in Korea, let me use the Google translator to understand even more than in the English.
Program're really well use
But there comes a PING TTL know whether to boot from any operating system, I think would help.

**Comment by basildane** [comment]
Greetings Korea!

TTL stands for "Time to live".  See the [Wikipedia](https://en.wikipedia.org/wiki/Time_to_live) article.
You can probably keep it set to the default of 128 unless you have a specific reason to change it.

Ping is used to test if a computer is online.  The word comes from the sound of a submarine's SONAR.  It sends a "Ping" and listens for an echo.  If it hears the echo, then it knows the computer is online.

We can translate the application into Korean if you want to help.  I can help you get started.
