### ISSUE TITLE
Socket access forbidden

### ISSUE THREAD

**Issue by rodpumas** [basildane/WakeOnLAN#21]
Get the error message: An attempt was made to access a socket in a way forbidden by its access permissions when trying to connect to a host.
I tried disabling simple TCP IP services that was suggested in another post and it didn't help.

I followed the getting started page.
[wake on lan error.docx](https://github.com/basildane/WakeOnLAN/files/275061/wake.on.lan.error.docx)

**Comment by basildane** [comment]
Please run `netstat -ab` and look for a line that has **UDP    0.0.0.0:9              *:***
The next line will indicate the name of the application that has port 9 locked.

**Comment by basildane** [comment]
Please let me know what you find.  I would like to improve the documentation on this.

**Comment by rodpumas** [comment]
I'll run it and let you know the results. Thanks for the quick reply.

**Comment by rodpumas** [comment]
I ran netstat -ab and UDP 0.0.0.0.9 listed the application running as tcpsvcs.exe

**Comment by basildane** [comment]
That would be simple tcpip services.  You need to disable that in services.  I suggest you remove the feature from Windows, unless you are actually using it, which I've never seen happen.
