### ISSUE TITLE
tip: default network device

### ISSUE THREAD

**Issue by dgdedomingo** [basildane/WakeOnLAN#22]
Hello,

Perhaps it would be useful, create an option in the general settings for select the default network device.

Thanks

**Comment by basildane** [comment]
I was thinking it might be useful to have WOL packets sent on all networks, instead of forcing the user to pick one.  Any thoughts?

**Comment by basildane** [comment]
This is now in prototype stage in 2.11.11 beta 10.

**Comment by basildane** [comment]
I have made a major change in this and it is in [2.11.11-beta.15](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.11-beta.15).

There is no longer a need to configure the interface.  It is automatic.  Please help test.
