### ISSUE TITLE
Shutdown issues: $HOST substitution, and command line

### ISSUE THREAD

**Issue by Vectorspace000** [basildane/WakeOnLAN#23]
Hi

I am trying to follow these examples to set up shutdown for a linux server:
http://wol.aquilatech.com/help/shutdown/default.html
http://wol.aquilatech.com/help/command_line/default.html
I am using plink.exe to send a shutdown command, just as in the example

I have two issues.

First, it does not seem to like $HOST in:
`plink.exe -ssh -pw $PASS $USER@$HOST "shutdown command"`
With the command like this, nothing happens. I have to replace $HOST with the actual server name for the command to work. Where exactly does it take $HOST from? The Name field on the Display Properties tab is exactly the same as the server name.

Second, I cannot get the command line shutdown via WakeOnLanC to work. With the command configured as: 
`plink.exe -ssh -pw $PASS $USER@servername "shutdown command"`
It will work when I select shutdown from within the WakeOnLan program. But when I try and do a shutdown from the command line using WakeOnLanC I get an access denied error and a password prompt:
`C:\>WakeOnLanC -s -m servername`
`WakeOnLan Command Line 2.11.10.0`
`Shutdown sent to servername...Successful`
` `
`C:\>Access denied`
`$USER@servername's password:`
I think that $USER substitution does not work from the command line so it is telling plink to use user name $USER instead of substituting the actual user from the credentials, so plink is displaying the access denied message and password prompt?

Any advice is appreciated.

**Comment by basildane** [comment]
Sorry for the difficulty you are having here.
Looking at that code, it appears that the substitution variables are only supported in the GUI, not the command line module.

The good news is that code is very simple and we should be able to fix this easily.

**Comment by Vectorspace000** [comment]
Thank you!

My first question about $HOST - to clarify, that issue is in the GUI.

**Comment by basildane** [comment]
OK, I will check that function.

**Comment by basildane** [comment]
I just tested with the GUI.  The $HOST is replaced by the FQDN of the machine.  It worked.  $USER and $PASS worked too.

However, this rule will not work with Localhost, only for remote computers.  This is because shutdown of localhost is a different process.  Were you trying to shutdown a remote computer?

**Comment by Vectorspace000** [comment]
Yes it's a remote server. For this issue, I assumed that whatever field $HOST comes from was not specified correctly, but I didn't know which field that was. Now I know it's FQDN.

The FQDN/IP field on the Wake Up tab was set to the IP address of the remote server. I changed it to the server name and now both Wake Up and Shut Down work in the GUI.

So my $HOST issue is sorted, thanks! I look forward to when the command line fix gets released.

**Comment by basildane** [comment]
Please try [2.11.10 beta 10](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.10-beta.10).  This should fix the substitution variables in the command line program.

**Comment by Vectorspace000** [comment]
It worked! Thank you very much!

**Comment by basildane** [comment]
Thanks for testing.  I will release this soon.
