### ISSUE TITLE
No Hot Buttons

### ISSUE THREAD

**Issue by jpdonato** [basildane/WakeOnLAN#24]
Hi, I wish to use Wake On Lan version 2.11.10 to manage a domain containing Windows 7, 10 and even Server 2003 R2 computers. I currently just installed Wake On Lan version 2.11.10 on a Windows 10 32-bit client and, as expected, it detected some computers. However, when I press the "Hot Buttons" in the main window menu, the new pane appears at the right, however it contains no buttons at all: "Start All" and "Emergency Shutdown" are missing. No matter how I resize or play with the window or pane, they never appear. The right pane is completely greyed out. Is this an issue with 2.11.10 or am I doing something wrong? Best regards,

**Comment by basildane** [comment]
Hi jpdonato, I see you closed this ticket, did you find the problem?  What was the solution?

**Comment by jpdonato** [comment]
Hi Basildane,


Yes I closed the ticket because I found the cause and the solution. The cause is that instead of using standard font size in Windows, I use a slightly larger setting. Because of this, I had to drag the vertical frame bar to the left (not the window, the frame); this way the two large icons appeared. Not the best fix, but a suitable workaround.


Regards,


jpdonato


________________________________
