### ISSUE TITLE
Schedule greyed out

### ISSUE THREAD

**Issue by aosp-manager** [basildane/WakeOnLAN#28]
Hi, on a Windows 2003 server, just installed your WOL software but the schedule button (and menu option) are greyed out. Is this a known issue? Services like Scheduler are running fine.
Also,  small issue (hardly worth mentioning!!!) but it can't wake up any Window 10 PCs which is a pity since I've just upgraded all the network PC's to W10.
I found your software because I wanted to start the PC's before people come in so it can run it's software updates/virus scans at a quiet time.
Many thanks
Adrian

**Comment by basildane** [comment]
The scheduling system uses version 2 of the Windows Task Scheduler.  This is available on 2008 server, or Vista and higher.  XP and 2003 are not supported for scheduling.  Sorry.

Windows 10 is fully supported.  Most likely, you need to update your NIC drivers or check the configuration to make sure WOL is enabled on them.  Please check that and let me know.
