### ISSUE TITLE
Remote shutdown schedule from a locked computer 

### ISSUE THREAD

**Issue by jlampe1985** [basildane/WakeOnLAN#29]
I have you WOL software on a workstation on your network. Where running peer to peer. Is it possible to schedule tasks like shutdown a group of pcs and have it run from a locked pc. The lock pc isn't the pcs that I want to remotely shutdown it is the workstation that has to software installed.

**Comment by basildane** [comment]
Yes it is possible, you will have to try it.  It can be complex to get Windows to login to remote computers this way, especially when they are not in a domain.

It should not matter that the WOL computer is locked.  The scheduler uses the Windows Task Scheduler, and it doesn't matter if it is locked or not.  Just test everything manually before hand.  If the remote computer is logged in, then you will need to specify "force" to force it to shutdown while someone is logged into it.

**Comment by jlampe1985** [comment]
Thanks, 

I just realized that I didn't check force apps to shutdown.
