### ISSUE TITLE
User preferences for View > Toolbar and View > Status Bar not restored on app start

### ISSUE THREAD

**Issue by IC-SteveP** [basildane/WakeOnLAN#3]
Most user View preferences (i.e. Show Groups, Show Hot Buttons, etc) are restored on app start.  The user's View preference for Toolbar and Status Bar are not restored, these UI elements are always displayed on app start.

If this is considered to be desirable behaviour it would nice to be able to override it in Tools > Options.

Cheers,
    Steve

(WOL v2.11.4, Win7 SP1 x64)

P.S. Very usable app and great docs ... nicely done!

**Comment by basildane** [comment]
You are correct, a couple of settings are not being preserved.  I'm checking into that.  Thanks.

**Comment by basildane** [comment]
This is all fixed in 2.11.4 beta 20, and will be in the next release.
