### ISSUE TITLE
Save Host Password for RDP

### ISSUE THREAD

**Issue by LordStanley** [basildane/WakeOnLAN#33]
In the Properties for the Host I'd like to be able to save the RDP password so i don't have to enter it every time I connect to the Host.

**Comment by basildane** [comment]
Hi, I just wanted to say this is a great idea and sorry it took so long to respond.

**Comment by LordStanley** [comment]
You could also provide the rest of the options that the RDP executable mstsc allows in the properties too if you wish.. I can see the /f /w /h window size options to being used by some..

Too bad that there isn't an option to turn off desktop composition that some computers require..

**Comment by basildane** [comment]
This is now in the [2.11.12 beta 20 build](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.12-beta.20).
You can link an RDP file to a host.  You can also edit the RDP settings by clicking the 'edit' button.
If you save the credentials using RDP, then you can go right into a remote server with one click.

**Comment by LordStanley** [comment]
Works perfect.. thanks for adding this.. I'll be sending in a donation soon

**Comment by basildane** [comment]
Thanks for testing and reporting back.
