### ISSUE TITLE
Enhancement: Disable splash screen in settings

### ISSUE THREAD

**Issue by ham2016** [basildane/WakeOnLAN#36]
It would be very nice if the splash screen (which shows at startup) could be disabled in the settings.

**Comment by brando-calrissian** [comment]
This would be great. It's a bit distracting / awkward to see the splash screen when you have WOL set up to start with Windows.. imagine if even just a handful of autostart apps did this?

**Comment by basildane** [comment]
No problem, will be in the next build.  It's crazy busy here now.
