### ISSUE TITLE
WOL windows 10

### ISSUE THREAD

**Issue by marv9n** [basildane/WakeOnLAN#37]
Hey guys,

I have 12 computers I used to use WOL to manage (shutdown / startup). However since ugprading to windows 10 on these I receive Access denied errors. I have allowed power management on the network cards and have turned off fast boot. Any ideas?

Thanks,

**Comment by basildane** [comment]
You mean access denied on Shutdown, right?
Are they on a domain?
You need to configure credentials for shutdown on the tab.

Wake up does not have any credentials.

**Comment by marv9n** [comment]
Hey - yes they are on a domain. I have just manged to shut four of the 12 down by changing the shutdown type from WMI to legacy... This doesn't seem to affect the others however, I am checking to see what the difference is, might be at BIOS level... 

Adding credentials isn't helping, and the four that I have working didn't seem to need them either?

**Comment by marv9n** [comment]
Figured out the issue, needed to add domain users to the administrator group on each individual host as well as the legacy change. Some of the PCs already had this which is why they were working.

Cheers

**Comment by basildane** [comment]
Thanks for updating us on what you did.
If you don't feel comfortable granting ADMIN to that user, you only need to add the GPO to allow remote shutdown for that user.

Glad you got it working.
