### ISSUE TITLE
WakeOnLAN Batch not working after W10-Updates

### ISSUE THREAD

**Issue by 1956-01** [basildane/WakeOnLAN#39]
High,

after some W10-Updates, may be October'2016, WakeOnLanC (Batch) does not work anymore on my PC.
Version 2.11.11.

Please see ScreenShot.

Before, and on any other PC's without Auto-Update-W10, all works fine!!!

mfg
Gerhard 

![wakeuponlanc](https://cloud.githubusercontent.com/assets/23343413/20111994/c7e0516a-a5ea-11e6-8f8a-1f0b3b722efe.JPG)

**Comment by basildane** [comment]
My first guess is that your selected interface `-if 192.168.0.90` is not matching the network that it is trying to send on, therefore the out-of-context error.

However, in version 2.11.12, which came out last week, I have removed the -if parameter, and all the interface handling is simplified and automatic.  Can I request that you update to 2.11.12 and test again?

**Comment by basildane** [comment]
Also, are you still using the default port 9 for wake up?  If you changed it to an invalid port such as 0, that would also return this error.

**Comment by 1956-01** [comment]
High,

wauuuuuh,

so fast ..

I have not changed anything !!!
Just updated W10.
And any other PC's (without auto-update w10) are still working.

Never the less i will try the new version ..
Please give me some time ...
YOU CAN REQUEST TEST THE 2.11.12 !!!

mfg
Gerhard

**Comment by basildane** [comment]
Please check the ip address of your test machine.  You will find that 192.168.0.90 is not one of the valid interfaces.

**Comment by 1956-01** [comment]
Your are RIGHT !
IP-Adress has changed.
Now it's working fine, like all times before.

Updated to 2.11.12.
Delete the -IF paramter.
Works fine too.

Thank you very much.
