### ISSUE TITLE
Socket issue on Windows 10 x64

### ISSUE THREAD

**Issue by BillBugSplat** [basildane/WakeOnLAN#4]
Great utility!  Unfortunately, I've recently run into a snag.

I began to see this issue after upgrading from Win7 to Win10.  All was well up to that point.

I tried running as admin, but no change.  

![wol issue](https://cloud.githubusercontent.com/assets/7950279/12789059/390758aa-ca6a-11e5-9782-c84ea90fd98c.png)

**Comment by BillBugSplat** [comment]
Forgot to mention that the error occurs when I attempt to wake a device by right-clicking and selecting 'Wake Up'

**Comment by basildane** [comment]
Hi, this error indicates that port 9 is in use by another process.
Usually, this would be simple tcp services.
See if these suggestions help: [http://wol.aquilatech.com/help/troubleshooting/listener.html](url)

**Comment by BillBugSplat** [comment]
Yes, that's the problem for sure.  I also recently enabled these.  Thanks so much!
