### ISSUE TITLE
Command Line I/O exception

### ISSUE THREAD

**Issue by kecarbaugh** [basildane/WakeOnLAN#42]
When installing to a different directory than the default, the command line interface fails with a file not found exception looking for the machine.xml file in the default directory.  This only happens when the machine name provided via the -m option is not found.

**Comment by basildane** [comment]
Yes, you would need to specify the location of the database using the -p option, if it is moved.
It could be fixed so that moving the default location would carry over by default, to the command line.  I will make a note of it.

**Comment by basildane** [comment]
This is now in the [2.11.12 beta 20 build](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.12-beta.20).
The command line will default default to finding the database in the same path as the GUI.  The -p option is still usable too.
