### ISSUE TITLE
An interesting feature

### ISSUE THREAD

**Issue by rahaman0786** [basildane/WakeOnLAN#45]
Hi,

thank you for your soft, it is exactly what I need but...it's not worked for me ! In my case I use WLAN WoL and it need more than one WoL packet to wake up my computer.
I used the android application "WoL Wake on Lan Wan". It is possible to put a number of WoL packet and an interval in second between them. I use 5 packets with 1s interval and it definitely works.

Could you please add this kind of feature in your next release?

Thank you

Cheers

Rahaman

**Comment by basildane** [comment]
Working on it...

**Comment by basildane** [comment]
Please test here [2.11.13 beta 10](https://github.com/basildane/WakeOnLAN/releases/tag/2.11.13-beta.10)
You can set the number of repeats in the host's properties.
You can also set the time interval between repeats in system properties.
![capture3](https://cloud.githubusercontent.com/assets/9865861/21063647/bb33e074-be24-11e6-9133-1234acda9ac0.PNG)
![capture4](https://cloud.githubusercontent.com/assets/9865861/21063653/c063d0a4-be24-11e6-9e75-899cb57bf8d2.PNG)

**Comment by basildane** [comment]
rahaman0786, were you able to test the feature?
