### ISSUE TITLE
WakeOnLanC.exe can't execute wakeup command

### ISSUE THREAD

**Issue by MaxGTO** [basildane/WakeOnLAN#49]
Hi
I install WakeOnLan.exe in my personal computer, but I just want to use WakeOnLanC.exe in my mobile computer. So, I copy "Machines.dll", "WakeOnLanC.exe" and "WOL.dll" to my mobile computer.
When I use WakeOnLanC.exe wake my system, I will see the fail issue as like below:
![image](https://cloud.githubusercontent.com/assets/24908928/21632776/7d542eca-d284-11e6-951e-8138dc1b0a66.png)
Could I ask how can i do if I want to use WakeOnLanC.exe wake system?
Thank you so much.

**Comment by basildane** [comment]
You cannot just copy DLLs to another machine, they have to be installed.  Can you run the setup program on the mobile computer to install the application?  Then you will be able to run WakeOnLanC.

You could probably manually register the DLL's too, but it's probably not wise.

**Comment by EddyVB** [comment]
Hello,
I have the same error message.
Clean install latest version on new win10 machine.
C:\Program Files\Aquila Technology\WakeOnLAN>wakeonlanc -w -mac 00:11:32:xx:xx:xx
WakeOnLan Command Line 2.11.14.0

Onverwerkte uitzondering: System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij WakeOnLanC.Module1.DoWakeup()
   bij WakeOnLanC.Module1.Main()

**Comment by EddyVB** [comment]
Me again,
Got it working.
I opened the gui version, and selected 'listening''and pinging', and got a windows firewall remark to approve connection. Got back to the CLI version, executed the file again, now windows comes back with also a firewall approvement question. Now it works.. Win did not ask anything before opening the gui. 
(So Max, check maybe the win firewall.)

**Comment by basildane** [comment]
I just uninstalled and reinstalled, tried wakeonlanc and it worked, I am having trouble duplicating the problem.  I can try a clean machine, but that will take time.

**Comment by MaxGTO** [comment]
Hi All,
I found if system has existed the registry as below that can fix this issue.
![image](https://cloud.githubusercontent.com/assets/24908928/21795612/2d3776c2-d73e-11e6-8bd7-d549b0d8e215.png)

**Comment by basildane** [comment]
Got it, fixing this now...
