### ISSUE TITLE
Schedule tasks problem | please help

### ISSUE THREAD

**Issue by nholweg** [basildane/WakeOnLAN#5]
Hello,

I can't seem to figure out what I am possibly doing wrong here.. I am trying to add timed tasks but it keeps giving me the following error: 0x08007052E . I am sure the username and password are correct. 

The computer I am trying to add in the scheduler for sleep is a Windows 7 Enterprise machine.
It is set up to automaticly login on startup @ netplwiz
When I manually execute the tasks they work.

I will add a screenshot here [It is Dutch, saying the user credentials are wrong]:

![image](https://cloud.githubusercontent.com/assets/17292041/13106941/4bf2d186-d56b-11e5-9a88-7dbc175b80a1.png)

Some help would be very appreciated.

**Comment by basildane** [comment]
Sorry, I'm really swamped with work.  This error indicates your local account to configure the scheduled task is not working.  Are you on a domain or is it a local account?  You have to specify an account for the windows task scheduler to use as a context to run jobs in the background.

Specifically, this says your password is wrong, but it could be that you have not correctly entered the domain\userid.  I think for a local account, you use machine\userid.

**Comment by nholweg** [comment]
Thank you for your response.

The computers aint running in a domain. I tried using the
computername\username but this also won't work.

The remote computer is configured in netplwiz on Automaticly log in so
maybe this is the problem? This has to be on as these computer  is used as
info screen.

I will try again tomorrow.
Op 18 feb. 2016 16:41 schreef "basildane" <notifications@github.com>:

**Comment by nholweg** [comment]
I have tried doing what you said but it didn't quiet work.
This time it gives me another error;

(40,4):LogonType:
(screenshot;)

[image: Inline afbeelding 1]

Any idea how to get around this?









2016-02-18 16:49 GMT+01:00 niek holweg <niekholweg@gmail.com>:

**Comment by basildane** [comment]
I've tried for years to find out from Microsoft what that error means.  They do not know, even though it is their API.  Anyway, there is SOMETHING wrong with your logon ID.

I would create a standard scheduled task in windows task scheduler, and see if that account works that way.  I have a test machine here and it works using machine\user and password.

Also, just for testing, use an account that is a local administrator.

Unfortunately, this code was designed for domain users, and it get's rather complicated sometimes with local users.

**Comment by basildane** [comment]
Oh, and it could have something to do with the account not having rights to logon-as-batch, or some other attribute.  That's why I suggest you try it manually to see if windows gives you a readable error.

**Comment by nholweg** [comment]
I tried several different things but still don't understand what I am doing wrong. But oh well, it works when I shut down the computers manually, which is great already. 

Testing it on the way you said is quiet difficult for me as the same thing happens to about 10 computers.

Thank you for your time.

**Comment by nholweg** [comment]
Oh and isn't there a way I can send tasks to the program using Windows Scheduler? Like by adding a new task, selecting WoL (.exe) and add tasks such as /start-all ? Things like this work on some programs like for example MBAM aswell and I am wondering if this is possible for WoL.

**Comment by basildane** [comment]
I'm just asking for you to send me a screenshot of your Trigger setup, so that I can troubleshoot the problem.

**Comment by nholweg** [comment]
[image: Inline afbeelding 3][image: Inline afbeelding 4][image: Inline
afbeelding 1][image: Inline afbeelding 2]

2016-02-23 13:30 GMT+01:00 basildane <notifications@github.com>:

**Comment by basildane** [comment]
Yes, you can create your own scheduled tasks manually.  WOL uses the Windows task scheduler.  It uses the command line WOL to do this.  The command line options are documented here [http://wol.aquilatech.com/help/command_line/default.html](url)

Did you try using an administrator account?

**Comment by nholweg** [comment]
Yes. The account we use is Administrator. I will try out the Windows task scheduler. Thank you.

**Comment by basildane** [comment]
sorry, the reply asking for a screenshot was a mistake, that was not intended for you.

**Comment by basildane** [comment]
Let me know if I can help you with the command line.

**Comment by nholweg** [comment]
Well I got the commandline thing working. I think I will make a few batch files and make the central computer which controls the other ones do the work with Windows Scheduler.
