### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by Anatoliyr210** [basildane/WakeOnLAN#51]
There is a tick - "Auto start when system start" but the program is not loaded when the computer boots.
Windows 10 64 bit

**Comment by basildane** [comment]
I just tested this and it is working normally for me.
Can you select "Auto start with windows", and then check to see if this registry entry is set:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\WakeOnLAN`
That key should contain the path to the WakeOnLAN program.  For example: 
`"C:\Program Files\Aquila Technology\WakeOnLAN\WakeOnLan.exe" /min`

Is it there?
