### ISSUE TITLE
Error: No such interface supported

### ISSUE THREAD

**Issue by gqmendoza** [basildane/WakeOnLAN#55]
I'm receiving an error when I try to shutdown my Windows 7 systems.  It's definitely a firewall issue because if I disable my firewall it will work.  I've opened up UDP port 9, allowed ICMPv4-In, allowed Windows Firewall Remote Management (RPC), allowed Windows Management Instrumentation (WMI-In), and allowed Distributed Transaction Coordinator (RPC) but no luck.  The actual Status is "Error: No such interface supportedNo such interface supported".  Since I have 175 devices I need to control, I've created some command lines for easier deployment.  Also, these devices are on a workgroup. (not to my liking but out of my control)

netsh advfirewall firewall add rule name="WOL - Open Port 9" dir=in action=allow protocol=UDP localport=9
netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" dir=in new action=allow
netsh advfirewall firewall set rule name="Windows Firewall Remote Management (RPC)" dir=in new action=allow
netsh advfirewall firewall set rule name="Windows Management Instrumentation (WMI-In)" dir=in new action=allow
netsh advfirewall firewall set rule name="Distributed Transaction Coordinator (RPC)" dir=in new action=allow

**Comment by basildane** [comment]
Shutdown requires full microsoft network connectivity.  I found some helpful information here. http://www.online-tech-tips.com/computer-tips/remote-shutdown-command/

**Comment by gqmendoza** [comment]
Thank you basildane.  There was a registry command in the link you provided that was my issue.  My systems are turning off and turning on the way they should be.  Thanks again!
