### ISSUE TITLE
WakeOnLAN HDD crashed

### ISSUE THREAD

**Issue by arre81** [basildane/WakeOnLAN#58]
Hi. Thanks for a really good software.

The computer I had WakeOnLAN installed on had a HDD crash.
When connecting the HDD externally to another computer the partition doesn't appear in explorer.
However I can extract the files using a recovery software.

What is the best way to recover the WakeOnLAN configuration when I can't start the software and export it?

**Comment by arre81** [comment]
It seems the Machines are available in C:\ProgramData\Aquila..\machines
When replacing that file with the one from the crashed computer the correct Machines appears in WakeOnLAN.
The Schedules however are another story.
It seems the least bad way to restore these are to copy them from C:\Windows\System32\Tasks\Aquila...
Then edit the files to see the times and other info.
Then recreate them manually from the information found in the files.

Guess I don't need more support here. Maybe someone else will benefit from this..

**Comment by basildane** [comment]
Sorry about your crash.  It has been requested before to backup the schedules.  Unfortunately I have not had time to implement that yet.

**Comment by basildane** [comment]
Oh, additional comment.
You can take your existing files in that folder and IMPORT them with Windows Task Scheduler.  You do not need to recreate them by hand.

**Comment by arre81** [comment]
Thanks for the input! That worked.
I created a temp scueduled activity in WakeOnLAN so the Aquila folder appeared in the Windows task scheduler.
I then imported the files into that folder in Windows task scheduler.
Afterwards when starting WakeOnLAN, the tasks were in the Schedule tab.
Perhaps there should be a guide for this somewhere (or maybe there already is).
