### ISSUE TITLE
Bugs in 2.11.5

### ISSUE THREAD

**Issue by websurfer83** [basildane/WakeOnLAN#7]
Hello,
thank you for the new version 2.11.5.

Unfortunately, there are some bugs in this version. I had version 2.11.4 installed and made the upgrade to 2.11.5. The previous version was set to German language in the settings menu. The XML file is on a network share.

If I start the 2.11.5 the first time, everything is good. The language is still in German and I can see my computers, which are in the xml file.

When I start the 2.11.5 a second time, the application is in English and the computer window is empty. I change the language to German and re-import the xml-file, but after restarting the application, the problems come again.

Even unistalling the 2.11.4 and doing a clean install of the 2.11.5 could not solve the problem.

The problem exists on diffirent computers with Windows 7, Windows 8.1 and Windows Server 2012 R2.

I hope that you can fix this problems with a new build.

Thanks and kind regards
websurfer83.

**Comment by basildane** [comment]
Thank you for taking the time to report this.  I see that there is a logic error in the "culture" handler.  I'm working on it now.

I think if you click on a "group" on the left pane, you will see your computers again.  They are not missing.  I will try and fix this as quickly as possible.

**Comment by basildane** [comment]
Please try 2.11.5 beta 10.
https://github.com/basildane/WakeOnLAN/releases/tag/2.11.5-beta.10

I think this will fix the problem.

**Comment by basildane** [comment]
Fixed in 2.11.6.

**Comment by websurfer83** [comment]
Hello,
thanks for fixing the bug. 2.11.6 works fine!

**Comment by basildane** [comment]
Glad to hear that.
