### ISSUE TITLE
One computer in group shows offline - but from only one computer in the group

### ISSUE THREAD

**Issue by Curtis1015** [basildane/WakeOnLAN#82]
I have WOL installed on multiple computers on a local LAN. From one of the computers WOL displays the status of a specific computer as offline while all the rest show it as online.

From the computer that is showing the computer of concern as offline I can successfully ping to the destination computer.

I can use the WOL tool Search for Machines to find and add the destination computer in question. So, the MAC address and IP address are correct.

Trying to figure out what is different about this one computer or WOL on that computer that causes this difference. The WOL level is the same on all computers involved - 2.11.18.

**Comment by basildane** [comment]
It is probably the way you have the computer identified in WOL.  I would use the FQDN if you can.  Is it a DHCP host?

You can try turning on debug log (Tools -> Debug Log) then startup the pinger.

**Comment by Curtis1015** [comment]
Ok.

Must be some computer gremlins at work. The "problem" seem to have fixed itself.

All systems a go at the moment.  By the way, all systems involved are DHCP hosts.

**Comment by basildane** [comment]
If they are DHCP, in Status, you can leave the IP blank, it will resolve it for you.  Please let me know if you find a problem.
