### ISSUE TITLE
Ping OK but WOL unknown state

### ISSUE THREAD

**Issue by katzec3** [basildane/WakeOnLAN#84]
Hi Basildane!

Your WOL is very good for us! Thanx for developing!
I have already used it for 2 years!!
Now I have a problem with version 18  or earlier. Some versions ago (I don't know which one) worked perfectly.

I have some PCs which are running continuously, I use WOL for checking their status (Online,Offline).
But some days ago WOL put some PCs to unknown state. I tried to test and check the machine.xml
config but nothing. 
I reduced only two PCs in the config but the problem is same. The one IP is Online in WOL (IP...117), other one unknown (IP...122). Both are in same network, totally same PC. Both PC is OK by a normal cmd PING...
I don't know what's the problem.
Please check it!

Zoltán from Hungary

here is the machine.xml config:
`<?xml version="1.0" encoding="utf-8"?>
<ArrayOfMachine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Machine>
    <Name>Easy</Name>
    <MAC>00-A0-45-6D-F7-5B</MAC>
    <IP>10.197.204.122</IP>
    <Broadcast>10.197.204.255</Broadcast>
    <Netbios>HUSOP-NM0122</Netbios>
    <Method>0</Method>
    <Emergency>false</Emergency>
    <ShutdownCommand />
    <Group>Operator Flat</Group>
    <UDPPort>9</UDPPort>
    <TTL>128</TTL>
    <RDPPort>3389</RDPPort>
    <RDPFile />
    <Note />
    <UserID />
    <Password>RN3FDVHYYNb4bENKNTu46Q==</Password>
    <Domain />
    <ShutdownMethod>WMI</ShutdownMethod>
    <KeepAlive>false</KeepAlive>
    <RepeatCount>1</RepeatCount>
  </Machine>
  <Machine>
    <Name>Csomagoló1</Name>
    <MAC>00-A0-45-6D-F6-E5</MAC>
    <IP>10.197.204.117</IP>
    <Broadcast>10.197.204.255</Broadcast>
    <Netbios>HUSOP-NM0117</Netbios>
    <Method>0</Method>
    <Emergency>false</Emergency>
    <ShutdownCommand />
    <Group>Operator Flat</Group>
    <UDPPort>9</UDPPort>
    <TTL>128</TTL>
    <RDPPort>3389</RDPPort>
    <RDPFile />
    <Note />
    <UserID />
    <Password>RN3FDVHYYNb4bENKNTu46Q==</Password>
    <Domain />
    <ShutdownMethod>WMI</ShutdownMethod>
    <KeepAlive>false</KeepAlive>
    <RepeatCount>1</RepeatCount>
  </Machine>
</ArrayOfMachine>`

**Comment by basildane** [comment]
Can you disable the pinger, then turn on debug display (tools -> debug log), then turn on the pinger.
Let's look at the results of the log.

**Comment by katzec3** [comment]
Hi! I did it!

the machine config a bit differrent (other PC run now) but the problem is same.
current test machine config:
[machines.xml.txt](https://github.com/basildane/WakeOnLAN/files/1310294/machines.xml.txt)

debug log:
[debug_log_170918.txt](https://github.com/basildane/WakeOnLAN/files/1310288/debug_log_170918.txt)

thanks
Zoltán

**Comment by katzec3** [comment]
Hi Basildane!

I have found the problem!! Your debug help me.
I tried to ping names also and the problem was similar than in your WOL...
When I changed the URI from name to IP in WOL, everyone run fine :)

We have a DNS settings problem somewhere.. this is a wrong news for IT guy.

thanks a lot
Zoltán

**Comment by basildane** [comment]
That's great!  I was just looking at your files...
Thanks for the update.
