### ISSUE TITLE
IP Address shows ipv6 instead of ipv4 Info

### ISSUE THREAD

**Issue by MadMopar** [basildane/WakeOnLAN#86]
It seems with recent versions the ipv6 address shows instead of the ipv4 address.

How do I set it up so that the IPV4 address is shown as default.

Thanks

**Comment by basildane** [comment]
What it is doing is reporting the IP address that the operating system returns as the default, based on the FQDN you entered.

**Comment by MadMopar** [comment]
Is there a way to change it so that it reports the IPV4 address instead?  The only thing in the FQDN is the system name right now.

Thanks

**Comment by MadMopar** [comment]
> What it is doing is reporting the IP address that the operating system returns as the default, based on the FQDN you entered.

> Hi basildane.  Any idea how I can set this so that I see ipv4 adresses?

Thanks

**Comment by basildane** [comment]
I think the issue with ipv6 addresses is now fixed.  Here is [2.11.19 beta 50](https://cloud.aquilatech.com/s/jtyd6ofJODRXVdL).  I'm getting ready to release this.

**Comment by MadMopar** [comment]
That fixed the ipv4 vs ipv6 issue.

Thanks
