### ISSUE TITLE
Flickering Screen

### ISSUE THREAD

**Issue by MadMopar** [basildane/WakeOnLAN#87]
With version .18 the top third to half of the window keeps flickering.  If I reinstall .15, it doesn't.

Thanks

**Comment by basildane** [comment]
Please check [build beta 19.20](https://cloud.aquilatech.com/s/y8wNrqXrxYFpZtB).
I think this fixed the flickering issue.

**Comment by basildane** [comment]
Were you able to test build 19.20?

**Comment by MadMopar** [comment]
I installed it and so far there hasn't been anymore flickering.

Thanks

**Comment by MadMopar** [comment]
Issue resolved with 19.20
