### ISSUE TITLE
Shutdown: passwords with vertical line (pipe) character fails

### ISSUE THREAD

**Issue by kamilmirza** [basildane/WakeOnLAN#92]
when i initiate shutdown on a machine with password containing vertical line (pipe) character it fails 
and shows this error:
`Error: 'ephant' is not recognized as an internal or external command, operable program or batch file`
my password is = e|ephant

changed the password without pipe character and it works
win10x64 v1709 with registery key 
keyboard: US English

**Comment by basildane** [comment]
Which shutdown method are you using?
WMI, Legacy, or Custom?

**Comment by kamilmirza** [comment]
Custom - Emergency Shutdown checked
have computers in WORKGROUP

**Comment by basildane** [comment]
I tested with that password and it worked for me.  So, would you please upload a trace log?
Go to Tools and check "Trace Log".
Then try to shutdown that host.  Close WOL and upload the file "My Documents\wakeonlan.tracelog" to [uploads](https://cloud.aquilatech.com/s/cKHVPHPXfaYdbjn).  It is a secure, private location.

Thank you.

**Comment by kamilmirza** [comment]
tracelog file uploaded

**Comment by basildane** [comment]
Thanks, i see it, but the tracelog does not show you doing the "shutdown".  That's the part I need to see.

**Comment by kamilmirza** [comment]
lol i did initiated the Shutdown process twice for the log
i'll try again

**Comment by basildane** [comment]
ok, how about this.  Could you tell me the exact shutdown custom command you are using?  That's what I'm really after.

**Comment by kamilmirza** [comment]
if i remember correctly, the use of quotation marks/inverted commas does the trick with passwords
uploaded new tracelog with 3 tries of Shutdown

**Comment by basildane** [comment]
For some reason it is not including the shutdown in the trace.  So, could you share the command string you are using?

**Comment by kamilmirza** [comment]
before WakeOnLAN by Aquila Technology
i was using
`shutdown.exe /s /m \\COMPUTERNAME /t 00`

followed **TxRedCat** reply on [THIS](https://social.technet.microsoft.com/Forums/windows/en-US/4cd01733-0f21-4078-979d-5080bc0c98fb/remote-shutdown-access-denied-5)

**Comment by basildane** [comment]
I need to see the exact command string you are using in WOL so that I can duplicate the issue.

**Comment by kamilmirza** [comment]
i'm not using any command in WOL

password = e|ephant 
is set in Shutdown tab, with Legacy method and Emergency Shutdown

here is the proof:
![2018-01-30_18-04-49](https://user-images.githubusercontent.com/6561475/35567810-25dca242-05e8-11e8-9853-89eaa72e2132.gif)

**Comment by basildane** [comment]
This is fixed in 2.11.21 beta 10.  You can download [here](https://cloud.aquilatech.com/s/OSWHcUEh2MODOkk).

**Comment by basildane** [comment]
Which tool do you prefer to create that screen capture?

**Comment by kamilmirza** [comment]
2.11.21 beta 10 fixed it!!!
thanks 👍

**Comment by kamilmirza** [comment]
i use [ShareX](https://getsharex.com/) Screen Recording (GIF) option

**Comment by kamilmirza** [comment]
one more thing i would like to ask

how can we reduce the shutdown interval?
i tried giving the command line option: `-t 05` but
shutdown does gets initiated but it waits for 30sec after the pop-up

**Comment by basildane** [comment]
Yes, the Legacy option is hard-coded at 30 seconds.  The reasoning was that with Legacy mode, that gives the destination user time to cancel the shutdown.  With WMI, the notification is sent separately, so it's less of an issue.

I really want to get rid of Legacy, but there are a lot of users out there that have no other choice but to use that method.

**Comment by basildane** [comment]
Have you tried WMI and did it not work for you?

**Comment by kamilmirza** [comment]
no it does not work because my machines are in WORKGROUP
and it shows `RPC server is unavailable`

**Comment by kamilmirza** [comment]
how can we add delay in WMI method?
its instant and does not show any shutdown pop-up

**Comment by basildane** [comment]
With WMI, you specify the delay in the shutdown screen.  The field is "Timeout".  It should display the shutdown message on the hosts, wait for the timeout, then shutdown.

At least that's how it SHOULD work.

**Comment by kamilmirza** [comment]
just tried it and no Shutdown warning appeared on the host with WMI 
plus Message option does not show any message on the host

**Comment by basildane** [comment]
if you are in a workgroup and RPC isn't working, then the message function won't work.
You can test it by opening a command prompt and typing this command:
**msg * /server:COMPUTERNAME "a test message"**

If you get an error, then it's not possible to send a message without changing permissions.

**Comment by kamilmirza** [comment]
tried `msg * /server:COMPUTERNAME "a test message"` with no dice, not important for now, anyways
what should i do to display Shutdown warning (WMI method) with configured Timeout? 
on Legacy method, it shows the Shutdown warning

**Comment by basildane** [comment]
That indicates it's not going to work in WOL either, however, I'm working on a client/server solution that may fix that.
